### ISSUE TITLE
Lorem ipsum.txt is not installed

### ISSUE THREAD

**Issue by scarabeusiv** [jaraco/jaraco.text#4]
Whnen installing 3.2.0 package the error goes as follows:

```
[    5s] /usr/lib/python2.7/site-packages/jaraco/text/__init__.py:232: in <module>
[    5s]     lorem_ipsum = resources.read_text(__name__, 'Lorem ipsum.txt')
[    5s] /usr/lib/python2.7/site-packages/importlib_resources/_py2.py:118: in read_text
[    5s]     with open_text(package, resource, encoding, errors) as fp:
[    5s] /usr/lib/python2.7/site-packages/importlib_resources/_py2.py:97: in open_text
[    5s]     raise FileNotFoundError(message)
[    5s] E   OSError: 'Lorem ipsum.txt' resource not found in 'jaraco.text'
```

As a workaround I just copy the file in package generating phase, but i guess it should be done properly by the setup.py install:
 %python_expand install -Dm 0644 jaraco/text/*.txt %{buildroot}%{$python_sitelib}/jaraco/text/

**Comment by jaraco** [comment]
Thanks for the report and apologies for taking this long to notice it.

Looking at the implementation, the module will simply fail to import if that file isn't present, so it should be easy to replicate the reported issue, but I'm unable to do so:

```
~ $ pip-run -q --no-binary jaraco.text jaraco.text==3.2.0 -- -c "import jaraco.text; print(jaraco.text.lorem_ipsum[:11])"
Lorem ipsum
~ $ pip-run -q jaraco.text==3.2.0 -- -c "import jaraco.text; print(jaraco.text.lorem_ipsum[:11])"
Lorem ipsum
```

My guess is you're installing from a github tarball or some other format that doesn't include the necessary metadata to ensure that file is present, but clearly it is in the repository, in the tests, and in the released versions. It's included in the build through the use of the [include_package_data directive](https://github.com/jaraco/jaraco.text/blob/e843daad79e1c2933835cc804a549f43f3123194/setup.cfg#L18) and the [use of setuptools_scm](https://github.com/jaraco/jaraco.text/blob/e843daad79e1c2933835cc804a549f43f3123194/pyproject.toml#L2) for file finding.

I recommend to always install from the released artifacts or if you must from the Git Repo checkout, and use PEP 518 compliant builders (pip, [build](https://pypi.org/project/build)) to build the project.

Good luck and let me know if you're still experiencing the issue after addressing these considerations.
